"""
Chuỗi giao diện (nhãn nút, tab, thông báo) của app du khách.

- Tiếng Anh là bản GỐC để dịch máy sang các ngôn ngữ khác.
- Tiếng Việt viết tay (chất lượng tốt nhất cho khách trong nước).
- 14 ngôn ngữ còn lại: hệ thống tự dịch lần đầu có người dùng rồi lưu lại (UiTextService).
"""

UI_STRINGS_EN: dict[str, str] = {
    "appTitle": "Linh Ung Pagoda Audio Guide",
    "shortTitle": "Linh Ung Pagoda",
    "gateIntro": "Listen to automatic narration as you walk to each point of interest. 16 languages supported.",
    "priceLabel": "Price",
    "durationLabel": "Valid for",
    "hours": "hours",
    "payOnline": "Pay online",
    "haveCode": "I have an access code",
    "cashHint": "Pay cash at the ticket counter and the staff will give you a 6-character code.",
    "enter": "Enter",
    "tabMap": "Map",
    "tabList": "Places",
    "tabRoute": "Route",
    "tabChat": "Ask",
    "myLocation": "My location",
    "simulate": "Simulate GPS",
    "auto": "Auto play",
    "chooseTour": "Choose a route",
    "suggestRoute": "Suggest order",
    "autoPick": "Main places",
    "chatPlaceholder": "Type a question about the pagoda...",
    "chatHello": "Hi, I'm the virtual guide of Linh Ung Pagoda. Ask me about its history, architecture, places to see, opening hours, how to get there...",
    "send": "Send",
    "you": "You",
    "guide": "Guide",
    "close": "Close",
    "fallbackNote": "No translation yet, showing",
    "makeAudio": "Translate and make audio",
    "speak": "Read with device voice",
    "noAudio": "no audio yet",
    "hasAudio": "audio",
    "near": "You are near",
    "meters": "m",
    "minutes": "min",
    "walk": "walk",
    "listen": "listen",
    "locating": "Getting GPS position...",
    "gpsDenied": 'GPS not available. Tick "Simulate GPS" and tap the map to set your position.',
    "simulateOn": "Simulating: tap the map to set your position",
    "gpsAccuracy": "GPS accuracy:",
    "paymentPending": "Waiting for payment confirmation...",
    "paymentFailed": "Payment failed",
    "sources": "Sources",
    "total": "Total",
    "processing": "Processing...",
    "expired": "Access expired, please enter a new code",
    "translating": "Translating content into your language...",
    "translated": "Content is now in your language",
    "detailsTitle": "Details",
    "hoursLabel": "Opening hours",
    "hoursUnknown": "No information yet",
    "showWeek": "Show all week",
    "closedAllDay": "Closed",
    "today": "Today",
    "tomorrow": "Tomorrow",
    "statusOpen": "Open",
    "statusClosingSoon": "Closes soon",
    "statusClosed": "Closed",
    "statusOpeningSoon": "Opens soon",
    "closesAt": "Closes at",
    "opensAt": "Opens at",
    "feeLabel": "Entrance fee",
    "free": "Free",
    "visitLabel": "Suggested visit",
    "about": "about",
    "amenitiesLabel": "Facilities and rules",
    "tipsLabel": "Tips",
    "popularLabel": "Popular times",
    "notEnoughData": "Not enough data yet, needs more visits",
    "busyNow": "Right now",
    "busyLow": "usually not busy",
    "busyMedium": "a little busy",
    "busyHigh": "usually very busy",
    "directions": "Directions (Google Maps)",
    "cat_gate": "Gate",
    "cat_statue": "Statue",
    "cat_hall": "Worship hall",
    "cat_garden": "Garden",
    "cat_viewpoint": "Viewpoint",
    "cat_landmark": "Landmark",
    "cat_service": "Services",
    "amenity_wheelchair": "Wheelchair accessible",
    "amenity_stairs": "Many stairs",
    "amenity_parking": "Parking",
    "amenity_restroom": "Restrooms",
    "amenity_drinking_water": "Drinking water",
    "amenity_shade": "Shade and benches",
    "amenity_photo_ok": "Photos allowed",
    "amenity_no_photo_ceremony": "No photos during ceremonies",
    "amenity_shoes_off": "Remove shoes before entering",
    "amenity_quiet_zone": "Please keep quiet",
    "amenity_dress_code": "Modest clothing required",
}

UI_STRINGS_VI: dict[str, str] = {
    "appTitle": "Thuyết minh Chùa Linh Ứng",
    "shortTitle": "Chùa Linh Ứng",
    "gateIntro": "Nghe thuyết minh tự động khi bạn đi tới từng điểm tham quan. Hỗ trợ 16 ngôn ngữ.",
    "priceLabel": "Giá vé",
    "durationLabel": "Thời gian dùng",
    "hours": "giờ",
    "payOnline": "Thanh toán online",
    "haveCode": "Đã có mã truy cập",
    "cashHint": "Trả tiền mặt tại quầy vé, nhân viên sẽ đưa bạn mã 6 ký tự.",
    "enter": "Vào",
    "tabMap": "Bản đồ",
    "tabList": "Danh sách",
    "tabRoute": "Lộ trình",
    "tabChat": "Hỏi đáp",
    "myLocation": "Vị trí của tôi",
    "simulate": "Giả lập GPS",
    "auto": "Tự phát",
    "chooseTour": "Chọn lộ trình",
    "suggestRoute": "Gợi ý thứ tự đi",
    "autoPick": "Các điểm chính",
    "chatPlaceholder": "Nhập câu hỏi về chùa...",
    "chatHello": "Chào bạn, mình là hướng dẫn viên ảo của Chùa Linh Ứng. Bạn cứ hỏi về lịch sử, kiến trúc, các điểm tham quan, giờ mở cửa, đường đi... nhé.",
    "send": "Gửi",
    "you": "Bạn",
    "guide": "Hướng dẫn viên",
    "close": "Đóng",
    "fallbackNote": "Chưa có bản dịch, đang hiển thị bằng",
    "makeAudio": "Dịch và tạo audio",
    "speak": "Đọc bằng giọng máy",
    "noAudio": "chưa có audio",
    "hasAudio": "có audio",
    "near": "Bạn đang ở gần",
    "meters": "m",
    "minutes": "phút",
    "walk": "đi bộ",
    "listen": "nghe",
    "locating": "Đang lấy vị trí GPS...",
    "gpsDenied": 'Không lấy được GPS. Tick "Giả lập GPS" rồi bấm vào bản đồ để chọn vị trí.',
    "simulateOn": "Đang giả lập: bấm vào bản đồ để đặt vị trí",
    "gpsAccuracy": "GPS: sai số",
    "paymentPending": "Đang chờ xác nhận thanh toán...",
    "paymentFailed": "Thanh toán không thành công",
    "sources": "Nguồn",
    "total": "Tổng",
    "processing": "Đang xử lý...",
    "expired": "Hết hạn sử dụng, vui lòng nhập mã mới",
    "translating": "Đang dịch nội dung sang ngôn ngữ bạn chọn...",
    "translated": "Đã chuyển sang ngôn ngữ bạn chọn",
    "detailsTitle": "Thông tin",
    "hoursLabel": "Giờ mở cửa",
    "hoursUnknown": "Chưa có thông tin",
    "showWeek": "Xem cả tuần",
    "closedAllDay": "Đóng cửa",
    "today": "Hôm nay",
    "tomorrow": "Ngày mai",
    "statusOpen": "Đang mở cửa",
    "statusClosingSoon": "Sắp đóng cửa",
    "statusClosed": "Đã đóng cửa",
    "statusOpeningSoon": "Sắp mở cửa",
    "closesAt": "Đóng cửa lúc",
    "opensAt": "Mở cửa lúc",
    "feeLabel": "Vé vào cửa",
    "free": "Miễn phí",
    "visitLabel": "Thời gian tham quan",
    "about": "khoảng",
    "amenitiesLabel": "Tiện ích và quy định",
    "tipsLabel": "Lưu ý",
    "popularLabel": "Khung giờ đông khách",
    "notEnoughData": "Chưa đủ dữ liệu, cần thêm lượt khách ghé thăm",
    "busyNow": "Bây giờ",
    "busyLow": "thường vắng",
    "busyMedium": "hơi đông",
    "busyHigh": "thường rất đông",
    "directions": "Chỉ đường (Google Maps)",
    "cat_gate": "Cổng chùa",
    "cat_statue": "Tượng Phật",
    "cat_hall": "Điện thờ",
    "cat_garden": "Vườn",
    "cat_viewpoint": "Điểm ngắm cảnh",
    "cat_landmark": "Điểm tham quan",
    "cat_service": "Khu dịch vụ",
    "amenity_wheelchair": "Lối đi cho xe lăn",
    "amenity_stairs": "Nhiều bậc thang",
    "amenity_parking": "Bãi gửi xe",
    "amenity_restroom": "Nhà vệ sinh",
    "amenity_drinking_water": "Nước uống",
    "amenity_shade": "Có bóng mát, ghế nghỉ",
    "amenity_photo_ok": "Được chụp ảnh",
    "amenity_no_photo_ceremony": "Không chụp ảnh khi hành lễ",
    "amenity_shoes_off": "Bỏ giày dép trước khi vào",
    "amenity_quiet_zone": "Giữ yên lặng",
    "amenity_dress_code": "Trang phục kín đáo",
}
